sudo: required

services:
  - docker

before_install:
  - docker pull fedora

install:
  - docker run -it --name build fedora /usr/bin/dnf -y install rpm-build rpmdevtools
  - docker commit build build
  - docker rm build

script:
  - docker run -it --rm -v $(pwd):/root/rpmbuild build /usr/bin/spectool -R -g /root/rpmbuild/SPECS/opensmtpd-extras.spec
  - docker run -it --rm -v $(pwd):/root/rpmbuild build /usr/bin/rpmbuild -bs /root/rpmbuild/SPECS/opensmtpd-extras.spec
