sudo: required
services:
- docker
before_install:
- docker pull mgruener/rpmbuild
- docker pull mgruener/copr-cli
- chmod -R o+rwX $(pwd)
env:
  global:
  - COPR_USERNAME=mgruener
  - COPR_COPR_URL=https://copr.fedoraproject.org
  - DOCKER_CMD="docker run -it --rm -v $(pwd):/home/rpmbuild/rpmbuild"
  - secure: BDk6UZpjREGsLD9reSZmneI3eAvOC1U1E65ctSy4NhFWkMMAmtUTNv4Tq1kpZ15jHbsky0wDcq2g/E6fYTUUc9ZVVgaDj9FtvAdNcjONV66bORVyRGG0Vz6vC+4hffjcZQ/RUUFvWLHhVLV8dXKiD20DWge50XCJOswEcOQlxerCRq2zQegIX1Vf4rhCLl/sv1mnoPW4Wuxp4AoVb9QhMuGkKrB7KDgAKO8V2clB1uoJlQ7FaZhK9b00Jr5jmtRCXYxzk6+ElZFU4iAbtYNvHLeaMpbKO7SWw8CsH4Wxeq4YYZaLszV9DIaZD8DvTXghVw4vBx4vflWQ/5KimnAIVLMT4hNsmT6DWiwnAKNhOxB1g7/7JA0SoD2x3G+iywNb90ZHL87KaAFAP3F2NXRehMn70rnC9i+Yl+WGefZrVGJE6Ozv41HLEdKyhZBWJedJq9/GkmR3wMMd8I5pSTQJgfmHCsc8ORp/J4GrIPRyQiUuFRPzIo1xPaebBiygE/5XY+fYTa6UILji97d1abbLIGRe/AuKc2w5eniA3LW/i0FWph8tpZp6qbcS8bzXFUNmnnLPGTnmlxp4IE+0g5nxjIPMgK/MAhRZivX9dzZSp65MGn1/AfgiUlClUMOAana+IJcs1LQ0IrXaQ3bzrceFs74NHmPhhE+bPLqKXYnHi6U=
  - secure: W/NBjSMNz3zOwbFNjMiXzoqXL0W5IP8ITq/N4FAcAN1fZl6LSQ2aRwmStol9ysHIEO+dfg6miYOiwiTWcu/254Ufj69ScxtUF+8BFJUvdPy3kxASTHe2TXZwia+y4hCs8/YAMvQW9ey3+Swo5PAy6aothFYo6A/PQwlyuMytdlrEdEbNDmvyO7FzvblLz/2xEQ83+YxxKK9H+jceWEn7Mo32bA0XQgu0y0DZYnLZIpbS2X+4qWM9OlaonycIuGqRL8r+jplPMQjkoxwfw2mG7el0Xuerhj8eRg+NDX+HsIFZgoloA2Q4yXEPDSJvMRFu8FhcNouUVd87CdeUEGp5yNrVrzvVDa1KrdXM7aQQoAYtdw4ZjfNt+IaPGU9MoLDG3z+HEzhaYDPc4yOYZTabmmGnAmrKF9OJk9mzuOfWfxTicD7tRaA3XxlyahEJRJ+6kPBHvzvxQzoSD487dAVEfeQgArv99Wq3Zx0XAv4vcTWKlS3UwzHbdKn2pa2Uf1PYIThCFCmPywUK0+stK54TgE0Tqen53xx+0T7VKjLng+y1HxXjKPlXuWTJ026gT+N5wW8RJWrIj+ziQ5W0pcJtwEM2YB96Xl8TOT0AIc8/R0d8BglthYP7TNIeNmSeAoRhblwsuAjPu/YQJf0mw/AFhQlwj5SVCQ8mEXAQLMM2FtI=
script:
- ${DOCKER_CMD} mgruener/rpmbuild /usr/bin/spectool -R -g rpmbuild/SPECS/opensmtpd-extras.spec
- ${DOCKER_CMD} mgruener/rpmbuild /usr/bin/rpmbuild -bs rpmbuild/SPECS/opensmtpd-extras.spec
- sudo chmod -R 0777 SRPMS
- ln -r -s SRPMS/*.rpm SRPMS/opensmtpd-extras-${TRAVIS_COMMIT}.src.rpm
- ${DOCKER_CMD}
  -e COPR_LOGIN=$COPR_LOGIN
  -e COPR_USERNAME=$COPR_USERNAME 
  -e COPR_TOKEN=$COPR_TOKEN 
  -e COPR_COPR_URL=$COPR_URL
  mgruener/copr-cli
  --debug build mgruener/opensmtpd-extras /home/rpmbuild/rpmbuild/SRPMS/opensmtpd-extras-${TRAVIS_COMMIT}.src.rpm
